server:
  port: ${SERVER_PORT:8088}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:commondb}
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
